# Generated by Django 4.0 on 2021-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='Detail',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
