# Generated by Django 3.2.7 on 2021-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_taskmodel_name_remove_taskmodel_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
