# Generated by Django 4.0 on 2021-12-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_taskmodel_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
